---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(github)

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(docker)

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(go)
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(go)
    groups:
      gotools:
        patterns:
          - "*"
