---
version: '2'
linters:
  default: all
  disable:
    - exhaustruct
    - paralleltest
    - testpackage
    - depguard
    - err113
    - revive
    - noinlineerr
    - wsl

  settings:
    funlen:
      lines: 100
      statements: 50

    tagliatelle:
      case:
        rules:
          json: snake

    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .LogWrap(
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

  exclusions:
    generated: lax
    rules:
      # Exclude lll issues for long lines with go:generate
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - dupl
          - goerr113
        path: _test\.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/floatme-corp/golflog)
    goimports:
      local-prefixes:
        - github.com/floatme-corp/golflog
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
