---
issue-845-fix: true
resolve-type-alias: false
with-expecter: true
disable-version-string: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/floatme-corp/golflog:
    interfaces:
      Configurator:
      BuildInfo:
