---
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName}}"
pkgname: mocks
filename: mocks.go
template: testify
packages:
  github.com/floatme-corp/golflog:
    interfaces:
      Configurator: {}
      BuildInfo: {}
