---
name: Codeball

"on":
  pull_request: {}
  pull_request_review_comment:
    types:
      - created
      - edited

jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Codeball
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "true"
          failJobsWhenReviewNeeded: "false"
          codeSuggestionsFromComments: "true"
