---
name: Commits

"on":
  pull_request:
    branches:
      - main

jobs:
  commit-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install conventional-commit linter
        run: |
          npm install @commitlint/config-conventional @commitlint/cli

      - name: Conventional commit check
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }}

      - name: No merge commits
        run: |
          BASE=${{ github.event.pull_request.base.sha }}
          HEAD=${{ github.event.pull_request.head.sha }}
          MERGES=$(git log --merges --ancestry-path "${BASE}..${HEAD}")

          # The merge list should be empty
          [[ ! -z "${MERGE}" ]] && {
            echo "PR contains merge commits:";
            echo "${MERGE}";
            exit 1;
          }
          exit 0;
