---
name: Test

"on":
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: make devkit.run
        env:
          WHAT: make coverage.out

      - name: Send Coveralls Coverage
        run: make devkit.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WHAT: make goveralls
