---
name: Test

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: make devkit.run
        env:
          WHAT: make coverage.xml

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
